export const categoryOptions = [
    {value: 'antiques', label: 'Antiques'},
    {value: 'appliances', label: 'Appliances'},
    {value: 'artsCrafts', label: 'Arts and Crafts'},
    {value: 'babyKidToys', label: 'Baby and Children Toys'},
    {value: 'babyKidClothes', label: 'Baby and Children Clothes'},
    {value: 'bikes', label: 'Bikes'},
    {value: 'books', label: 'Books'},
    {value: 'carTruckParts', label: 'Car or Truck Parts'},
    {value: 'cdsDvdsVhs', label: 'CDs/DVDs/VHSs'},
    {value: 'cellPhoneAcc', label: 'Cell Phone Acc'},
    {value: 'clothesMen', label: 'Clothes- Men'},
    {value: 'clothesWomen', label: 'Clothes- Women'},
    {value: 'computerAndAcc', label: 'Computer And Accessories'},
    {value: 'electronics', label: 'Electronics'},
    {value: 'gardening', label: 'Gardening'},
    {value: 'furniture', label: 'Furniture'},
    {value: 'household', label: 'Household'},
    {value: 'jewelery', label: 'Jewelery'},
    {value: 'musicalInst', label: 'Musical Instruments'},
    {value: 'rvCamping', label: 'RV and Camping'},
    {value: 'sportEqu', label: 'Sports Equipment'},
    {value: 'tools', label: 'Tools'},
    {value: 'toysGames', label: 'Toys and Games'},
    {value: 'videoGames', label: 'Video Games'},
]